name: Validate K8s Helm Chart
inputs:
  docker_namespace:
    required: false
    type: string
    default: 'syd.ocir.io/coexservices01'
  env:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: "check ${{inputs.env}} k8s helm charts"
      run: |
        docker run --rm \
          -v "$(pwd):/apps" \
          -w /apps \
          ${{inputs.docker_namespace}}/alpine/helm:3.9.0 \
          template -f /apps/k8s/values/values.${{inputs.env}}.yaml --set "version=${{ github.run_number }}" /apps/k8s/ --debug
