name: Test Maven Project

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      build_args:
        required: false
        type: string
        default: ''
      java_version:
        required: false
        type: string
        default: '17'

jobs:
  test-mvn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master
      - name: 'Authenticate Snyk CLI'
        run: snyk auth ${{secrets.SNYK_AUTH_TOKEN}}

      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ inputs.java_version }}'
          distribution: 'temurin'
          cache: maven

      - name: 'Setup github packages maven settings file'
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[ { "id": "github", "url": "https://maven.pkg.github.com/coexservices/*" } ]'
          servers: '[ { "id": "github", "username": "${GITHUB_ACTOR}", "password": "${GITHUB_TOKEN}" } ]'
        env:
          GITHUB_ACTOR: ${{ secrets.CES_GITHUB_PACKAGES_READ_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.CES_GITHUB_PACKAGES_READ_TOKEN }}

      - name: "Build with Maven | version: ${{ github.run_number }}"
        run: |
          mvn --batch-mode versions:set -DnewVersion=${{ github.run_number }}
          mvn --batch-mode clean install ${{ inputs.build_args }}

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          job_name: validate-pr
