name: Validate PR and commit formats

on:
  workflow_call:
    inputs:
      check_all_commit_msg:
        required: false
        type: boolean
        default: true

jobs:
  validate-commit-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check PR and commit formats
        uses: gsactions/commit-message-checker@v2
        if: github.event_name != 'workflow_dispatch'
        with:
          pattern: '^[A-Z][A-Z0-9]+-[0-9]+: .*$'
          error: |
            Your commit message and your PR title must follow the format of 'JIRA-123: ' 
            Did you forget to add your jira?
            Did you follow the correct format?

            Please follow this format so Jira can auto detect what is in each release.
            The regex is '^[A-Z][A-Z0-9]+-[0-9]+: .*$'
          checkAllCommitMessages: ${{ inputs.check_all_commit_msg }}
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true