name: Validate K8s

on:
  workflow_call:
    inputs:
      docker_namespace:
        required: false
        type: string
        default: 'syd.ocir.io/coexservices01'

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: |
          docker login ${{ inputs.docker_namespace }} -u ${{ secrets.ORACLE_CONTAINER_REGISTRY_DOCKER_USERNAME }} -p "${{ secrets.ORACLE_CONTAINER_REGISTRY_DOCKER_PASSWORD }}"

      - name: "check sit k8s helm charts"
        run: |
          docker run --rm \
            -v "$(pwd):/apps" \
            -w /apps \
            ${{inputs.docker_namespace}}/alpine/helm:3.9.0 \
            template -f /apps/k8s/values/values.sit.yaml --set "version=${{ github.run_number }}" /apps/k8s/ --debug

      - name: "check uat k8s helm charts"
        run: |
          docker run --rm \
            -v "$(pwd):/apps" \
            -w /apps \
            ${{inputs.docker_namespace}}/alpine/helm:3.9.0 \
            template -f /apps/k8s/values/values.uat.yaml --set "version=${{ github.run_number }}" /apps/k8s/ --debug

      - name: "check prod k8s helm charts"
        run: |
          docker run --rm \
            -v "$(pwd):/apps" \
            -w /apps \
            ${{inputs.docker_namespace}}/alpine/helm:3.9.0 \
            template -f /apps/k8s/values/values.prod.yaml --set "version=${{ github.run_number }}" /apps/k8s/ --debug
